//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.03 at 11:51:32 PM MSK 
//


package ru.dna.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="app" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="finalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="progress" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="trackingUI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trackingUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="diagnostics" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="clusterId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="applicationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="applicationTags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="startedTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="finishedTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="elapsedTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="amContainerLogs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amHostHttpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="masterNodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="allocatedMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="allocatedVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="reservedMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="reservedVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="runningContainers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="memorySeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="vcoreSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="queueUsagePercentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="clusterUsagePercentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="resourceSecondsMap">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="entry" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="preemptedResourceMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="preemptedResourceVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numNonAMContainerPreempted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numAMContainerPreempted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="preemptedMemorySeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="preemptedVcoreSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="preemptedResourceSecondsMap">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="entry" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="logAggregationStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="unmanagedApplication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amNodeLabelExpression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="timeouts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="timeout">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="expiryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="remainingTimeInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "app"
})
@XmlRootElement(name = "apps")
public class Apps {

    @XmlElement(required = true)
    protected List<Apps.App> app;

    /**
     * Gets the value of the app property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the app property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Apps.App }
     * 
     * 
     */
    public List<Apps.App> getApp() {
        if (app == null) {
            app = new ArrayList<Apps.App>();
        }
        return this.app;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="finalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="progress" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="trackingUI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trackingUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="diagnostics" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="clusterId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="applicationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="applicationTags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="startedTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="finishedTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="elapsedTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="amContainerLogs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="amHostHttpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="masterNodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="allocatedMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="allocatedVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="reservedMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="reservedVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="runningContainers" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="memorySeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="vcoreSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="queueUsagePercentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="clusterUsagePercentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="resourceSecondsMap">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="entry" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="preemptedResourceMB" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="preemptedResourceVCores" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numNonAMContainerPreempted" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numAMContainerPreempted" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="preemptedMemorySeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="preemptedVcoreSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="preemptedResourceSecondsMap">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="entry" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="logAggregationStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="unmanagedApplication" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="amNodeLabelExpression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="timeouts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="timeout">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="expiryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="remainingTimeInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "user",
        "name",
        "queue",
        "state",
        "finalStatus",
        "progress",
        "trackingUI",
        "trackingUrl",
        "diagnostics",
        "clusterId",
        "applicationType",
        "applicationTags",
        "priority",
        "startedTime",
        "finishedTime",
        "elapsedTime",
        "amContainerLogs",
        "amHostHttpAddress",
        "masterNodeId",
        "allocatedMB",
        "allocatedVCores",
        "reservedMB",
        "reservedVCores",
        "runningContainers",
        "memorySeconds",
        "vcoreSeconds",
        "queueUsagePercentage",
        "clusterUsagePercentage",
        "resourceSecondsMap",
        "preemptedResourceMB",
        "preemptedResourceVCores",
        "numNonAMContainerPreempted",
        "numAMContainerPreempted",
        "preemptedMemorySeconds",
        "preemptedVcoreSeconds",
        "preemptedResourceSecondsMap",
        "logAggregationStatus",
        "unmanagedApplication",
        "amNodeLabelExpression",
        "timeouts"
    })
    public static class App {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String user;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String queue;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(required = true)
        protected String finalStatus;
        protected int progress;
        @XmlElement(required = true)
        protected String trackingUI;
        @XmlElement(required = true)
        protected String trackingUrl;
        @XmlElement(required = true)
        protected String diagnostics;
        protected int clusterId;
        @XmlElement(required = true)
        protected String applicationType;
        @XmlElement(required = true)
        protected String applicationTags;
        protected int priority;
        protected long startedTime;
        protected long finishedTime;
        protected long elapsedTime;
        @XmlElement(required = true)
        protected String amContainerLogs;
        @XmlElement(required = true)
        protected String amHostHttpAddress;
        @XmlElement(required = true)
        protected String masterNodeId;
        protected int allocatedMB;
        protected int allocatedVCores;
        protected int reservedMB;
        protected int reservedVCores;
        protected int runningContainers;
        protected int memorySeconds;
        protected int vcoreSeconds;
        protected int queueUsagePercentage;
        protected int clusterUsagePercentage;
        @XmlElement(required = true)
        protected Apps.App.ResourceSecondsMap resourceSecondsMap;
        protected int preemptedResourceMB;
        protected int preemptedResourceVCores;
        protected int numNonAMContainerPreempted;
        protected int numAMContainerPreempted;
        protected int preemptedMemorySeconds;
        protected int preemptedVcoreSeconds;
        @XmlElement(required = true)
        protected Apps.App.PreemptedResourceSecondsMap preemptedResourceSecondsMap;
        @XmlElement(required = true)
        protected String logAggregationStatus;
        @XmlElement(required = true)
        protected String unmanagedApplication;
        @XmlElement(required = true)
        protected Object amNodeLabelExpression;
        @XmlElement(required = true)
        protected Apps.App.Timeouts timeouts;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUser(String value) {
            this.user = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the queue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueue() {
            return queue;
        }

        /**
         * Sets the value of the queue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueue(String value) {
            this.queue = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the finalStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFinalStatus() {
            return finalStatus;
        }

        /**
         * Sets the value of the finalStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFinalStatus(String value) {
            this.finalStatus = value;
        }

        /**
         * Gets the value of the progress property.
         * 
         */
        public int getProgress() {
            return progress;
        }

        /**
         * Sets the value of the progress property.
         * 
         */
        public void setProgress(int value) {
            this.progress = value;
        }

        /**
         * Gets the value of the trackingUI property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrackingUI() {
            return trackingUI;
        }

        /**
         * Sets the value of the trackingUI property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrackingUI(String value) {
            this.trackingUI = value;
        }

        /**
         * Gets the value of the trackingUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrackingUrl() {
            return trackingUrl;
        }

        /**
         * Sets the value of the trackingUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrackingUrl(String value) {
            this.trackingUrl = value;
        }

        /**
         * Gets the value of the diagnostics property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDiagnostics() {
            return diagnostics;
        }

        /**
         * Sets the value of the diagnostics property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDiagnostics(String value) {
            this.diagnostics = value;
        }

        /**
         * Gets the value of the clusterId property.
         * 
         */
        public int getClusterId() {
            return clusterId;
        }

        /**
         * Sets the value of the clusterId property.
         * 
         */
        public void setClusterId(int value) {
            this.clusterId = value;
        }

        /**
         * Gets the value of the applicationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationType() {
            return applicationType;
        }

        /**
         * Sets the value of the applicationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationType(String value) {
            this.applicationType = value;
        }

        /**
         * Gets the value of the applicationTags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationTags() {
            return applicationTags;
        }

        /**
         * Sets the value of the applicationTags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationTags(String value) {
            this.applicationTags = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         */
        public int getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         */
        public void setPriority(int value) {
            this.priority = value;
        }

        /**
         * Gets the value of the startedTime property.
         * 
         */
        public long getStartedTime() {
            return startedTime;
        }

        /**
         * Sets the value of the startedTime property.
         * 
         */
        public void setStartedTime(long value) {
            this.startedTime = value;
        }

        /**
         * Gets the value of the finishedTime property.
         * 
         */
        public long getFinishedTime() {
            return finishedTime;
        }

        /**
         * Sets the value of the finishedTime property.
         * 
         */
        public void setFinishedTime(long value) {
            this.finishedTime = value;
        }

        /**
         * Gets the value of the elapsedTime property.
         * 
         */
        public long getElapsedTime() {
            return elapsedTime;
        }

        /**
         * Sets the value of the elapsedTime property.
         * 
         */
        public void setElapsedTime(long value) {
            this.elapsedTime = value;
        }

        /**
         * Gets the value of the amContainerLogs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmContainerLogs() {
            return amContainerLogs;
        }

        /**
         * Sets the value of the amContainerLogs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmContainerLogs(String value) {
            this.amContainerLogs = value;
        }

        /**
         * Gets the value of the amHostHttpAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmHostHttpAddress() {
            return amHostHttpAddress;
        }

        /**
         * Sets the value of the amHostHttpAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmHostHttpAddress(String value) {
            this.amHostHttpAddress = value;
        }

        /**
         * Gets the value of the masterNodeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMasterNodeId() {
            return masterNodeId;
        }

        /**
         * Sets the value of the masterNodeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMasterNodeId(String value) {
            this.masterNodeId = value;
        }

        /**
         * Gets the value of the allocatedMB property.
         * 
         */
        public int getAllocatedMB() {
            return allocatedMB;
        }

        /**
         * Sets the value of the allocatedMB property.
         * 
         */
        public void setAllocatedMB(int value) {
            this.allocatedMB = value;
        }

        /**
         * Gets the value of the allocatedVCores property.
         * 
         */
        public int getAllocatedVCores() {
            return allocatedVCores;
        }

        /**
         * Sets the value of the allocatedVCores property.
         * 
         */
        public void setAllocatedVCores(int value) {
            this.allocatedVCores = value;
        }

        /**
         * Gets the value of the reservedMB property.
         * 
         */
        public int getReservedMB() {
            return reservedMB;
        }

        /**
         * Sets the value of the reservedMB property.
         * 
         */
        public void setReservedMB(int value) {
            this.reservedMB = value;
        }

        /**
         * Gets the value of the reservedVCores property.
         * 
         */
        public int getReservedVCores() {
            return reservedVCores;
        }

        /**
         * Sets the value of the reservedVCores property.
         * 
         */
        public void setReservedVCores(int value) {
            this.reservedVCores = value;
        }

        /**
         * Gets the value of the runningContainers property.
         * 
         */
        public int getRunningContainers() {
            return runningContainers;
        }

        /**
         * Sets the value of the runningContainers property.
         * 
         */
        public void setRunningContainers(int value) {
            this.runningContainers = value;
        }

        /**
         * Gets the value of the memorySeconds property.
         * 
         */
        public int getMemorySeconds() {
            return memorySeconds;
        }

        /**
         * Sets the value of the memorySeconds property.
         * 
         */
        public void setMemorySeconds(int value) {
            this.memorySeconds = value;
        }

        /**
         * Gets the value of the vcoreSeconds property.
         * 
         */
        public int getVcoreSeconds() {
            return vcoreSeconds;
        }

        /**
         * Sets the value of the vcoreSeconds property.
         * 
         */
        public void setVcoreSeconds(int value) {
            this.vcoreSeconds = value;
        }

        /**
         * Gets the value of the queueUsagePercentage property.
         * 
         */
        public int getQueueUsagePercentage() {
            return queueUsagePercentage;
        }

        /**
         * Sets the value of the queueUsagePercentage property.
         * 
         */
        public void setQueueUsagePercentage(int value) {
            this.queueUsagePercentage = value;
        }

        /**
         * Gets the value of the clusterUsagePercentage property.
         * 
         */
        public int getClusterUsagePercentage() {
            return clusterUsagePercentage;
        }

        /**
         * Sets the value of the clusterUsagePercentage property.
         * 
         */
        public void setClusterUsagePercentage(int value) {
            this.clusterUsagePercentage = value;
        }

        /**
         * Gets the value of the resourceSecondsMap property.
         * 
         * @return
         *     possible object is
         *     {@link Apps.App.ResourceSecondsMap }
         *     
         */
        public Apps.App.ResourceSecondsMap getResourceSecondsMap() {
            return resourceSecondsMap;
        }

        /**
         * Sets the value of the resourceSecondsMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link Apps.App.ResourceSecondsMap }
         *     
         */
        public void setResourceSecondsMap(Apps.App.ResourceSecondsMap value) {
            this.resourceSecondsMap = value;
        }

        /**
         * Gets the value of the preemptedResourceMB property.
         * 
         */
        public int getPreemptedResourceMB() {
            return preemptedResourceMB;
        }

        /**
         * Sets the value of the preemptedResourceMB property.
         * 
         */
        public void setPreemptedResourceMB(int value) {
            this.preemptedResourceMB = value;
        }

        /**
         * Gets the value of the preemptedResourceVCores property.
         * 
         */
        public int getPreemptedResourceVCores() {
            return preemptedResourceVCores;
        }

        /**
         * Sets the value of the preemptedResourceVCores property.
         * 
         */
        public void setPreemptedResourceVCores(int value) {
            this.preemptedResourceVCores = value;
        }

        /**
         * Gets the value of the numNonAMContainerPreempted property.
         * 
         */
        public int getNumNonAMContainerPreempted() {
            return numNonAMContainerPreempted;
        }

        /**
         * Sets the value of the numNonAMContainerPreempted property.
         * 
         */
        public void setNumNonAMContainerPreempted(int value) {
            this.numNonAMContainerPreempted = value;
        }

        /**
         * Gets the value of the numAMContainerPreempted property.
         * 
         */
        public int getNumAMContainerPreempted() {
            return numAMContainerPreempted;
        }

        /**
         * Sets the value of the numAMContainerPreempted property.
         * 
         */
        public void setNumAMContainerPreempted(int value) {
            this.numAMContainerPreempted = value;
        }

        /**
         * Gets the value of the preemptedMemorySeconds property.
         * 
         */
        public int getPreemptedMemorySeconds() {
            return preemptedMemorySeconds;
        }

        /**
         * Sets the value of the preemptedMemorySeconds property.
         * 
         */
        public void setPreemptedMemorySeconds(int value) {
            this.preemptedMemorySeconds = value;
        }

        /**
         * Gets the value of the preemptedVcoreSeconds property.
         * 
         */
        public int getPreemptedVcoreSeconds() {
            return preemptedVcoreSeconds;
        }

        /**
         * Sets the value of the preemptedVcoreSeconds property.
         * 
         */
        public void setPreemptedVcoreSeconds(int value) {
            this.preemptedVcoreSeconds = value;
        }

        /**
         * Gets the value of the preemptedResourceSecondsMap property.
         * 
         * @return
         *     possible object is
         *     {@link Apps.App.PreemptedResourceSecondsMap }
         *     
         */
        public Apps.App.PreemptedResourceSecondsMap getPreemptedResourceSecondsMap() {
            return preemptedResourceSecondsMap;
        }

        /**
         * Sets the value of the preemptedResourceSecondsMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link Apps.App.PreemptedResourceSecondsMap }
         *     
         */
        public void setPreemptedResourceSecondsMap(Apps.App.PreemptedResourceSecondsMap value) {
            this.preemptedResourceSecondsMap = value;
        }

        /**
         * Gets the value of the logAggregationStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogAggregationStatus() {
            return logAggregationStatus;
        }

        /**
         * Sets the value of the logAggregationStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogAggregationStatus(String value) {
            this.logAggregationStatus = value;
        }

        /**
         * Gets the value of the unmanagedApplication property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnmanagedApplication() {
            return unmanagedApplication;
        }

        /**
         * Sets the value of the unmanagedApplication property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnmanagedApplication(String value) {
            this.unmanagedApplication = value;
        }

        /**
         * Gets the value of the amNodeLabelExpression property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAmNodeLabelExpression() {
            return amNodeLabelExpression;
        }

        /**
         * Sets the value of the amNodeLabelExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAmNodeLabelExpression(Object value) {
            this.amNodeLabelExpression = value;
        }

        /**
         * Gets the value of the timeouts property.
         * 
         * @return
         *     possible object is
         *     {@link Apps.App.Timeouts }
         *     
         */
        public Apps.App.Timeouts getTimeouts() {
            return timeouts;
        }

        /**
         * Sets the value of the timeouts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Apps.App.Timeouts }
         *     
         */
        public void setTimeouts(Apps.App.Timeouts value) {
            this.timeouts = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="entry" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entry"
        })
        public static class PreemptedResourceSecondsMap {

            @XmlElement(required = true)
            protected List<Apps.App.PreemptedResourceSecondsMap.Entry> entry;

            /**
             * Gets the value of the entry property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the entry property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEntry().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Apps.App.PreemptedResourceSecondsMap.Entry }
             * 
             * 
             */
            public List<Apps.App.PreemptedResourceSecondsMap.Entry> getEntry() {
                if (entry == null) {
                    entry = new ArrayList<Apps.App.PreemptedResourceSecondsMap.Entry>();
                }
                return this.entry;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "key",
                "value"
            })
            public static class Entry {

                @XmlElement(required = true)
                protected String key;
                protected int value;

                /**
                 * Gets the value of the key property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKey() {
                    return key;
                }

                /**
                 * Sets the value of the key property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKey(String value) {
                    this.key = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public int getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(int value) {
                    this.value = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="entry" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entry"
        })
        public static class ResourceSecondsMap {

            @XmlElement(required = true)
            protected List<Apps.App.ResourceSecondsMap.Entry> entry;

            /**
             * Gets the value of the entry property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the entry property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEntry().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Apps.App.ResourceSecondsMap.Entry }
             * 
             * 
             */
            public List<Apps.App.ResourceSecondsMap.Entry> getEntry() {
                if (entry == null) {
                    entry = new ArrayList<Apps.App.ResourceSecondsMap.Entry>();
                }
                return this.entry;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "key",
                "value"
            })
            public static class Entry {

                @XmlElement(required = true)
                protected String key;
                protected int value;

                /**
                 * Gets the value of the key property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKey() {
                    return key;
                }

                /**
                 * Sets the value of the key property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKey(String value) {
                    this.key = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public int getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(int value) {
                    this.value = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="timeout">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="expiryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="remainingTimeInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "timeout"
        })
        public static class Timeouts {

            @XmlElement(required = true)
            protected Apps.App.Timeouts.Timeout timeout;

            /**
             * Gets the value of the timeout property.
             * 
             * @return
             *     possible object is
             *     {@link Apps.App.Timeouts.Timeout }
             *     
             */
            public Apps.App.Timeouts.Timeout getTimeout() {
                return timeout;
            }

            /**
             * Sets the value of the timeout property.
             * 
             * @param value
             *     allowed object is
             *     {@link Apps.App.Timeouts.Timeout }
             *     
             */
            public void setTimeout(Apps.App.Timeouts.Timeout value) {
                this.timeout = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="expiryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="remainingTimeInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "type",
                "expiryTime",
                "remainingTimeInSeconds"
            })
            public static class Timeout {

                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected String expiryTime;
                protected int remainingTimeInSeconds;

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the expiryTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExpiryTime() {
                    return expiryTime;
                }

                /**
                 * Sets the value of the expiryTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExpiryTime(String value) {
                    this.expiryTime = value;
                }

                /**
                 * Gets the value of the remainingTimeInSeconds property.
                 * 
                 */
                public int getRemainingTimeInSeconds() {
                    return remainingTimeInSeconds;
                }

                /**
                 * Sets the value of the remainingTimeInSeconds property.
                 * 
                 */
                public void setRemainingTimeInSeconds(int value) {
                    this.remainingTimeInSeconds = value;
                }

            }

        }

    }

}
