//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.03 at 11:51:32 PM MSK 
//


package ru.rosbank.hdp.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.dna.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.dna.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Apps }
     * 
     */
    public Apps createApps() {
        return new Apps();
    }

    /**
     * Create an instance of {@link Apps.App }
     * 
     */
    public Apps.App createAppsApp() {
        return new Apps.App();
    }

    /**
     * Create an instance of {@link Apps.App.Timeouts }
     * 
     */
    public Apps.App.Timeouts createAppsAppTimeouts() {
        return new Apps.App.Timeouts();
    }

    /**
     * Create an instance of {@link Apps.App.PreemptedResourceSecondsMap }
     * 
     */
    public Apps.App.PreemptedResourceSecondsMap createAppsAppPreemptedResourceSecondsMap() {
        return new Apps.App.PreemptedResourceSecondsMap();
    }

    /**
     * Create an instance of {@link Apps.App.ResourceSecondsMap }
     * 
     */
    public Apps.App.ResourceSecondsMap createAppsAppResourceSecondsMap() {
        return new Apps.App.ResourceSecondsMap();
    }

    /**
     * Create an instance of {@link Apps.App.Timeouts.Timeout }
     * 
     */
    public Apps.App.Timeouts.Timeout createAppsAppTimeoutsTimeout() {
        return new Apps.App.Timeouts.Timeout();
    }

    /**
     * Create an instance of {@link Apps.App.PreemptedResourceSecondsMap.Entry }
     * 
     */
    public Apps.App.PreemptedResourceSecondsMap.Entry createAppsAppPreemptedResourceSecondsMapEntry() {
        return new Apps.App.PreemptedResourceSecondsMap.Entry();
    }

    /**
     * Create an instance of {@link Apps.App.ResourceSecondsMap.Entry }
     * 
     */
    public Apps.App.ResourceSecondsMap.Entry createAppsAppResourceSecondsMapEntry() {
        return new Apps.App.ResourceSecondsMap.Entry();
    }

}
